server:
  port: 8082

spring:
  application:
    name: report-processor

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/reports
    username: report_requester
    password: report_requester
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate.ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: secret
    password: secret
    protocol: smtp
    ssl: true
    debug: false

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    topic: reports.requests
    group-id: report-processor.main
    client-id-prefix: report-processor

logging:
  level:
    root: INFO