spring:
  application:
    name: report-processor
kafka:
  bootstrap-servers: localhost:9092
  consumer:
    topic: reports.requests
    group-id: report-processor.main
    client-id-prefix: report-processor
logging:
  level:
    root: INFO