spring:
  application:
    name: report-processor

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    ssl: true
    debug: false

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  consumer:
    topic: ${KAFKA_CONSUMER_TOPIC}
    group-id: ${KAFKA_CONSUMER_GROUP_ID}
    client-id-prefix: ${KAFKA_CONSUMER_CLIENT_ID_PREFIX}
  producer:
    topic: ${KAFKA_PRODUCER_TOPIC}
    sender-id: ${KAFKA_PRODUCER_SENDER_ID}
    sender-name: ${KAFKA_PRODUCER_SENDER_NAME}

server:
  port: 8082

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true

  mail:
    debug: false

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: TRACE