server:
  port: 8082

spring:
  application:
    name: report-processor

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate.ddl-auto: create
    show-sql: true

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    topic: reports.requests
    group-id: report-processor.main
    client-id-prefix: report-processor

logging:
  level:
    root: INFO